# Generated by Django 4.2.4 on 2024-06-04 12:37

import Yaocai.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Yaocai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('inventory', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=Yaocai.models.price_default, max_digits=6)),
                ('image', models.URLField()),
                ('CategoryType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Yaocai.categorytype')),
            ],
        ),
    ]
