# Generated by Django 4.2.4 on 2024-06-04 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Yaocai', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yaocai',
            old_name='CategoryType',
            new_name='categoryType',
        ),
    ]
