name: 自动部署

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH 命令拉取代码
        uses: appleboy/ssh-action@master
        with:
          host: 175.178.235.132
          username: root
          password: LDtxy2406,
          script: |
            if ! command -v git &> /dev/null
            then
              sudo apt-get -y install git
            fi
            cd /home/ubuntu/YCMallBackend/YCMallBackend
            # 删除源代码
            rm -r ./YCMallBackend
            # 拉取代码
            git clone https://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@github.com/davincilll/YCMallBackend.git
            sleep 30
            # 删除容器及镜像
            /home/ubuntu/YCMallBackend/delete.sh
